version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fastkart/frontend

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user
