version: 0.0
os: linux

files:
  - source: server/
    destination: /home/ec2-user/fastkart/backend
    overwrite: true

  - source: scripts/
    destination: /home/ec2-user/fastkart/backend/scripts
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 600
      runas: ec2-user

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 600
      runas: ec2-user

    - location: scripts/install.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: ec2-user



