version: 0.0
os: linux

files:
  - source: server/
    destination: /home/ec2-user/fastkart/backend
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: ec2-user

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 600
      runas: ec2-user

    - location: scripts/install.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: ec2-user


