version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - npm install  # Installing project dependencies
      - echo Making shell scripts executable...
      - chmod +x scripts/*.sh  # Ensure all shell scripts in the scripts directory are executable

  build:
    commands:
      - echo Building Angular SSR app...
      - npm run build:ssr  # Build SSR app (both browser and server parts)

artifacts:
  files:
    - '**/*'             # Include all built files
    - '!package-lock.json'  # Exclude package-lock.json to prevent deployment overwrite
  discard-paths: no       # Preserve folder structure

post_build:
  commands:
    - echo Copying built files to the deployment folder...
    - rm -rf /home/ec2-user/fastkart/frontend/*  # Optional: clear old files to avoid conflicts
    - cp -R dist/fastkart-frontend/* /home/ec2-user/fastkart/frontend  # Deploy only built files

  



  


