version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - npm install  # Installing project dependencies

  build:
    commands:
      - echo Making scripts executable...
      - chmod +x scripts/*.sh  # Ensure that the shell scripts have execute permissions
      - echo Building Angular SSR app...
      - npm run build:ssr  # This will build both the SSR browser and server parts

artifacts:
  base-directory: dist/fastkart-frontend  # 👈 anchor here
  files:
    - '**/*'
  discard-paths: no  # Keep the folder structure when deploying


