version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd fastkart/frontend  # Change directory to frontend
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - npm install  # Installing project dependencies
      - echo Making shell scripts executable...
      - chmod +x scripts/*.sh  # Ensure all shell scripts in the scripts directory are executable

  build:
    commands:
      - echo Building Angular SSR app...
      - npm run build:ssr  # Build SSR app (both browser and server parts)

artifacts:
  files:
    - '**/*'  # Include all files in dist folder
  discard-paths: no  # Preserve the folder structure

cache: {}

  # Specify the destination folder as per the appspec.yml
  



  


